### ISSUE TITLE
Change Require Stream to requrire readable stream

### ISSUE THREAD

**Issue by JamieBunyassi** [crypto-browserify/cipher-base#17]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `cipher-base@1.0.4` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/cipher-base/index.js b/node_modules/cipher-base/index.js
index 6728005..16426bf 100644
--- a/node_modules/cipher-base/index.js
+++ b/node_modules/cipher-base/index.js
@@ -1,5 +1,5 @@
 var Buffer = require('safe-buffer').Buffer
-var Transform = require('stream').Transform
+var Transform = require('readable-stream').Transform
 var StringDecoder = require('string_decoder').StringDecoder
 var inherits = require('inherits')
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ljharb** [comment]
I'm unclear why this is necessary.
