### ISSUE TITLE
Use browser friendly stream apis

### ISSUE THREAD

**Issue by useEffects** [crypto-browserify/cipher-base#24]
I am using crypto-browserify to use crypto library on browsers, which uses cipher-base, which uses stream api from node.

![Image](https://github.com/user-attachments/assets/7705b720-b01a-4e21-94e2-540c3ce8d8fb)

related: https://github.com/browserify/cipher-base/issues/22

**Comment by ljharb** [comment]
This is due to a bundler that’s not properly automatically polyfilling node modules. I’m not familiar with angular, but presumably it can be configured to handle this (as other broken-by-default bundlers can).

Duplicate of #17. Duplicate of #22.

**Comment by useEffects** [comment]
I am sorry, I dont understand whats stopping you to use stream-browserify instead of node:stream?

**Comment by ljharb** [comment]
This package can run in both node and browsers, and stream-browserify is never supposed to be used explicitly, only transparently swapped in for stream by working bundlers.
