### ISSUE TITLE
SyntaxError: missing ; before statement

### ISSUE THREAD

**Issue by pwang08** [crypto-browserify/cipher-base#6]

**Comment by calvinmetcalf** [comment]
can you be a little more specific ?

**Comment by pwang08** [comment]
Well, I'm so glad to hear from you. 

Currently we use browserify to bundle up our js dependencies. But on some android device, spidermonkey report this error: 

> ScriptingCore::compileScript fail:/data/data/xxxxx/files/game.js
> D/cocos2d-x debug info( 1789): JS: /data/data/xxxxx/files/game.js:64170:SyntaxError: missing ; before statement

Then we find the code in line 64170 from this package.

**Comment by calvinmetcalf** [comment]
what's on that line (and the lines around it)?

**Comment by pwang08** [comment]
<img width="532" alt="default" src="https://cloud.githubusercontent.com/assets/5799825/20421652/4954cbc4-ada0-11e6-9565-2f9b20727192.png">

Line 64170. Maybe it's not a good idea to omit semicolon in JavaScript library.

**Comment by dcousens** [comment]
That is perfectly valid JS,  not sure why you're getting that error.

@calvinmetcalf why bother with `finally` at all?

**Comment by calvinmetcalf** [comment]
that's a good question, um I might have been doing more work there originally?
